# nginx proxy address - http://172.17.0.1:8084

name: discourse
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  discourse:
    image: bitnami/discourse:latest
    pull_policy: always
    container_name: discourse-app
    restart: always
    logging: *default-logging
    networks:
      - discourse
      - proxy
      - cloudflare
    ports:
      - "172.17.0.1:8084:3000"
    environment:
      TZ: ${TZ:-America/New_York}
      DISCOURSE_HOST: ${BASE_HOST_NAME:-localhost}
      DISCOURSE_SITE_NAME: ${APP_ORG_NAME:-Discourse}
      DISCOURSE_USERNAME: ${APP_ADMIN_USER:-admin}
      DISCOURSE_PASSWORD: ${APP_ADMIN_PASS:-changeme_admin_password}
      DISCOURSE_EMAIL: ${APP_ADMIN_USER:-admin@example.com}
      DISCOURSE_DATABASE_HOST: discourse-db
      DISCOURSE_DATABASE_PORT_NUMBER: 5432
      DISCOURSE_DATABASE_USER: ${DB_USER_NAME:-discourse}
      DISCOURSE_DATABASE_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
      DISCOURSE_DATABASE_NAME: ${DB_CREATE_DATABASE_NAME:-discourse}
      DISCOURSE_REDIS_HOST: discourse-redis
      DISCOURSE_REDIS_PORT_NUMBER: 6379
      DISCOURSE_SMTP_HOST: ${EMAIL_SERVER_HOST:-172.17.0.1}
      DISCOURSE_SMTP_PORT: ${EMAIL_SERVER_PORT:-587}
      DISCOURSE_SMTP_USER: ${EMAIL_SERVER_LOGIN_NAME:-}
      DISCOURSE_SMTP_PASSWORD: ${EMAIL_SERVER_LOGIN_PASS:-}
      DISCOURSE_SMTP_PROTOCOL: tls
      DISCOURSE_SMTP_AUTH: login
      CONTAINER_NAME: discourse-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    volumes:
      - ./volumes/data/discourse:/bitnami/discourse
    depends_on:
      - discourse-db
      - discourse-redis
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://discourse-app:3000'
      - 'cloudflare.hostname=discourse.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.discourse-app.entrypoints=http'
      - 'traefik.http.routers.discourse-app-secure.tls=true'
      - 'traefik.http.routers.discourse-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.discourse-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.discourse-app.middlewares=discourse-app-https-redirect'
      - 'traefik.http.routers.discourse-app-secure.entrypoints=https'
      - 'traefik.http.routers.discourse-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.discourse-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.discourse-app-secure.service=discourse-app'
      - 'traefik.http.services.discourse-app.loadbalancer.server.port=3000'

  discourse-db:
    image: postgres:latest
    pull_policy: always
    container_name: discourse-db
    restart: always
    logging: *default-logging
    networks:
      - discourse
    environment:
      TZ: ${TZ:-America/New_York}
      POSTGRES_DB: ${DB_CREATE_DATABASE_NAME:-discourse}
      POSTGRES_USER: ${DB_USER_NAME:-discourse}
      POSTGRES_PASSWORD: ${DB_USER_PASS:-changeme_db_password}
      CONTAINER_NAME: discourse-db
    volumes:
      - ./volumes/data/db/postgres/discourse:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

  discourse-redis:
    image: redis:alpine
    pull_policy: always
    container_name: discourse-redis
    restart: always
    logging: *default-logging
    networks:
      - discourse
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: discourse-redis
    volumes:
      - ./volumes/data/db/redis/discourse:/data

networks:
  discourse:
    name: discourse
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
